steps:
- id: 'rebuild-node-files'
  name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'bash'
  args:
  - '-c' # pass what follows as a command to bash
  - |
    echo '{ "commitID":"$COMMIT_SHA", "buildID":"$BUILD_ID"}' > buildDetails
    npm install

- id: 'Create Container'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/peacepinot:$BUILD_ID', '.']

- id: 'Push Container to Registry'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/peacepinot:$BUILD_ID']

- id: 'Deploy to Cloud Run'
  name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'peacepinot'
    - '--platform=managed'
    - '--region=us-central1'
    - '--image'
    - 'gcr.io/$PROJECT_ID/peacepinot:$BUILD_ID'
#- id: 'Deploy to Cloud Run'
#  name: 'gcr.io/cloud-builders/gcloud'
#  args:
#  - 'set'
#  - 'image'
#  - 'deployment/frontend'
#  - 'webserver=gcr.io/$_IMAGE_REPO/peacepinot:$BUILD_ID'
#  env:
#  - 'CLOUDSDK_COMPUTE_ZONE=$_CLOUDSDK_COMPUTE_ZONE'
#  - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLOUDSDK_CONTAINER_CLUSTER'
#  - 'CLOUDSDK_CORE_PROJECT=$_CLOUDSDK_CORE_PROJECT'
