steps:
- id: 'Create Container'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$_IMAGE_REPO/peacepinot:$BUILD_ID', '.']

- id: 'Push Container to Staging registry'
  name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$_IMAGE_REPO/peacepinot:$BUILD_ID"]

- id: 'Deploy to K8s'
  name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/frontend'
  - 'webserver=gcr.io/$_IMAGE_REPO/peacepinot:$BUILD_ID'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=$_CLOUDSDK_COMPUTE_ZONE'
  - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLOUDSDK_CONTAINER_CLUSTER'
