steps:
- id: 'Create Container'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$_IMAGE_REPO/gcpdemo:$SHORT_SHA', '.']

- id: 'Push Container to Staging registry'
  name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$_IMAGE_REPO/gcpdemo:$SHORT_SHA"]

- id: 'Deploy and get Manifest'
  name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args:

  - '-c' # pass what follows as a command to bash
  - |
    gcloud container clusters get-credentials --zone=$_CLUSTER_ZONE --project=$_CLUSTER_PROJECT $_CLUSTER_NAME
    kubectl set image deployment/frontend-staging webserver=gcr.io/$_IMAGE_REPO/gcpdemo:$SHORT_SHA
# Prepare for github to store k8s config
